const PDFContent = async (projectInfo, htmlImageContent) => {
  return `
<html>
  <head>
    <meta charset="utf-8" />
    <title>Image Analysis Report</title>
    <style>
      body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        padding: 40px;
        color: #2c3e50;
        background-color: #f9f9f9;
        line-height: 1.6;
      }

      .header {
        text-align: center;
        margin-bottom: 40px;
      }
      .header h1 {
        font-size: 26px;
        color: #2c3e50;
        border-bottom: 3px solid #3498db;
        display: inline-block;
        padding-bottom: 5px;
        margin-top: 0;
      }

      .header-title {
        font-size: 28px;
        font-weight: bold;
        color: #2c3e50;
        position: relative;
      }

      .header-title::after {
        content: '';
        display: block;
        margin-top: 4px;
        width: 100%;
        height: 3px;
        background-color: #3498db;
      }

      .container {
        max-width: 800px;
        margin: 0 auto;
      }

      .section-title {
        font-size: 20px;
        font-weight: 600;
        margin: 40px 0 15px;
        border-left: 6px solid #3498db;
        padding-left: 12px;
        color: #2c3e50;
      }

      .project-info {
        background: #ffffff;
        padding: 20px;
        border-radius: 6px;
        box-shadow: 0 2px 6px rgba(0,0,0,0.05);
      }

      .project-info table {
        width: 100%;
        border-collapse: collapse;
      }

      .project-info td {
        padding: 10px;
        vertical-align: top;
        font-size: 14px;
      }

      .project-info td.label {
        font-weight: 600;
        width: 150px;
        color: #34495e;
        background: #f0f6fb;
      }

      .project-img {
        display: block;
        margin: 30px auto 0;
        max-width: 90%;
        border: 2px solid #ecf0f1;
        border-radius: 8px;
      }

      .chart {
        margin: 40px 0;
        text-align: center;
      }

      .chart img {
        max-width: 100%;
        border: 2px solid #ecf0f1;
        border-radius: 8px;
      }

      footer {
        text-align: center;
        font-size: 12px;
        color: #aaa;
        margin-top: 50px;
        border-top: 1px solid #eee;
        padding-top: 10px;
      }
      .page-break {
        page-break-before: always;
      }
      .header-logo{
        display: block;
        margin: 0 auto 10px;
        max-width: 180px;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <img src="https://www.mineexcellence.com/user/images/me-01.png" alt="Company Logo" class="header-logo" />
      <h1>Image Analysis Report</h1>
    </div>

    <div class="project-info">
      <div class="section-title">Project Information</div>
      <table>
        <tr>
          <td class="label">Project ID:</td>
          <td>${projectInfo.id}</td>
        </tr>
        <tr>
          <td class="label">Name:</td>
          <td>${projectInfo.name}</td>
        </tr>
        <tr>
          <td class="label">Image Name:</td>
          <td>${projectInfo.img_name}</td>
        </tr>
      </table>
      <img class="project-img" src="${projectInfo.img_url}" alt="Project Image" />
    </div>
    <div class="page-break"></div>
    <div class="section-title">Analyzed Graphs</div>
    <div class="chart">
      ${htmlImageContent}
    </div>

    <footer>
      Generated by MineExcellence | © ${new Date().getFullYear()}
    </footer>
  </body>
</html>
`;
};

export default PDFContent;
