/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/graphView` | `/graphView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projectView` | `/projectView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/taskview` | `/taskview`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workspace` | `/workspace`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/graphView` | `/graphView`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/projectView` | `/projectView`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/taskview` | `/taskview`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workspace` | `/workspace`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/graphView${`?${string}` | `#${string}` | ''}` | `/graphView${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/projectView${`?${string}` | `#${string}` | ''}` | `/projectView${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/taskview${`?${string}` | `#${string}` | ''}` | `/taskview${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workspace${`?${string}` | `#${string}` | ''}` | `/workspace${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/graphView` | `/graphView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projectView` | `/projectView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/taskview` | `/taskview`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workspace` | `/workspace`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
